### ISSUE TITLE
Questions on Support

### ISSUE THREAD

**Issue by designerbrent** [Faithlife/RefTaggerWordpressPlugin#10]
I'm wondering if this project is still being supported. There are many issues on the Wordpress support forum that are unaddress for months. https://wordpress.org/support/plugin/reftagger/

As far as my use of it goes, I'm getting close to removing it, because while it does provide functionality, it is also becoming a performance problem, and if these things are left uncared for, I will need to remove it.

**Comment by jfradleyFL** [comment]
Hi, this project is still supported. Some of the recent posts on the Wordpress site have fallen between the cracks, we're looking into it now.
