### ISSUE TITLE
Undefined index warnings

### ISSUE THREAD

**Issue by pedronebo** [Faithlife/RefTaggerWordpressPlugin#4]
I'm seeing quite a number of undefined index warnings on the RefTagger admin page in our dev environment. It only occurs when Wordpress is running in debug mode (WP_DEBUG) so the warnings aren't there in production.

Notice: Undefined index: submit in wp-content/plugins/reftagger/RefTagger.php on line 120

and when you click save changes...

Notice: Undefined index: lbs_libronix in wp-content/plugins/reftagger/RefTagger.php on line 160
Notice: Undefined index: lbs_convert_hyperlinks in wp-content/plugins/reftagger/RefTagger.php on line 166
Notice: Undefined index: lbs_case_insensitive in wp-content/plugins/reftagger/RefTagger.php on line 172
Notice: Undefined index: lbs_existing_libronix in wp-content/plugins/reftagger/RefTagger.php on line 178
Notice: Undefined index: lbs_tag_chapters in wp-content/plugins/reftagger/RefTagger.php on line 184
Notice: Undefined index: lbs_search_comments in wp-content/plugins/reftagger/RefTagger.php on line 202
Notice: Undefined index: lbs_nosearch_h4 in wp-content/plugins/reftagger/RefTagger.php on line 234
Notice: Undefined index: lbs_nosearch_h5 in wp-content/plugins/reftagger/RefTagger.php on line 240
Notice: Undefined index: lbs_nosearch_h6 in wp-content/plugins/reftagger/RefTagger.php on line 247
Notice: Undefined index: lbs_nosearch_b in wp-content/plugins/reftagger/RefTagger.php on line 254
Notice: Undefined index: lbs_nosearch_i in wp-content/plugins/reftagger/RefTagger.php on line 262
Notice: Undefined index: lbs_nosearch_u in wp-content/plugins/reftagger/RefTagger.php on line 269
Notice: Undefined index: lbs_nosearch_ol in wp-content/plugins/reftagger/RefTagger.php on line 276
Notice: Undefined index: lbs_nosearch_ul in wp-content/plugins/reftagger/RefTagger.php on line 282
Notice: Undefined index: lbs_nosearch_span in wp-content/plugins/reftagger/RefTagger.php on line 289

All the errors seem to be due to attempts to look up the $_REQUEST global array without first checking to see that the index exists. This may be the case when testing for a submit or checkboxes, if the submit button is not clicked or the checkboxes are not checked then the corresponding index will not exist in the $_REQUEST (or $_POST) arrays.

Note: the above list of warnings was with the defaults set on the admin page, so the checkboxes that are ticked by default are not listed here.

I've updated to the latest version 2.2.1 but I've also seen the same warning in previous releases.

see pull request #6

**Comment by pedronebo** [comment]
Any update on this?

**Comment by cjwilsontech** [comment]
Thanks for your report, this should be fixed now. Can you verify that this issue is resolved in the latest update to the plugin?

**Comment by pedronebo** [comment]
Excellent! Warnings are gone. Thank you
