### ISSUE TITLE
Google Console error: Unparsable structured data

### ISSUE THREAD

**Issue by pedronebo** [Faithlife/RefTaggerWordpressPlugin#5]
I maintain a Wordpress website with a Wocommerce store. Woocommerce inserts an ld+json schema at the bottom of each store page that Google use to find out information about the product. Some product descriptions have scripture references that are also included in the schema. Google console is reporting to me "Unparsable structured data > Parsing error: Missing ',' or '}'". It seems that Googlebot now understands changes to the DOM made by JavaScript and on inspection of the error I can see that RefTagger has added the anchor around the scripture reference and broken the JSON object. I've also confirmed that I can see this error directly on the page.

Schema information is contained in script tags:

`<script type="application/ld+json">
{
/* snip */
"description":"...(<a class="rtBibleRef" href="https://biblia.com/bible/nkjv/James%201.17" data-reference="James 1.17" data-version="nkjv" data-purpose="bible-reference" target="_blank">James 1:17</a>)."
/* snip */
}
</script>`

As you can see the JSON is broken by RefTagger when the content of script tags shouldn't be parsed at all. If I turn the RefTagger plugin off it changes back to just "(James 1:17)" as it should be.

I don't want to loose our ranking because we've used scripture references in our product descriptions.

**Comment by cjwilsontech** [comment]
Thanks for the report @pedronebo, we plan to have a fix for this out very soon! Thanks for your patience on this.

**Comment by pedronebo** [comment]
@cjwilsontech All good. I have a workaround for now. I've manually added "script" to the list of non-searchable tags (ie. lbs_nosearch) in the options table.

**Comment by cjwilsontech** [comment]
Deployed the fix for this (no Wordpress plugin update needed). Closing this issue, thanks again for the report!
