### ISSUE TITLE
Temp banned on Wordpress.org

### ISSUE THREAD

**Issue by Orrison** [Faithlife/RefTaggerWordpressPlugin#8]
Hey folks,

We use your plugin for our sites and as of Aug. 3rd 2020 can no longer install it due to it being banned on WP.

https://wordpress.org/plugins/reftagger/

Is there going to be an remediation to the issue and hopefully a restoration of good standing on the WP platform?

**Comment by bgrainger** [comment]
We're aware of the problem and are working to fix it.

**Comment by cjwilsontech** [comment]
Thanks for the report @Orrison, the plugin has been reinstated and is now available for download again.
